# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_name: 'Admin'
  admin_email: 'nagasundaram@ziniostech.com'
  admin_password: 'password'
  email_provider_username: "giftcard.mahindraretail@gmail.com" #TODO get the email details from MRPL admin and change
  email_provider_password: "mrpladmin"
  domain_name: "mahindraretail.com"
  secret_key_base: d12c8e3355ce2a6f97fa7d0d9e0eb535e923f09f1b0b5607da5ab08572de22d97e48e261d7c5fa3cc031e3b1bb2288ec7b0644299331ff09ef57d3a191206f85


production:
  admin_name: "Admin"
  admin_email: gcadmin@mahindraretail.com
  admin_password: 'password'
  email_provider_username: "giftcard.mahindraretail@gmail.com"
  email_provider_password: "mrpladmin"
  domain_name: "giftcard.mahindraretail.com"
  secret_key_base: 87e0b088b47409d5d0420971841babfaad4b4040a6425d56a5d83539b475c686b60dbf02a9923789d5efc424f3225f9097fabbeb1445d8c429194c138732123a
